const morningTab=document.querySelector('#morningTab'),eveningTab=document.querySelector('#eveningTab'),list=document.querySelector('#adhkar'),notifyBtn=document.querySelector('#notifyBtn'),nextPrayer=document.querySelector('#nextPrayer'),progressText=document.querySelector('#progressText'),progressLabel=document.querySelector('#progressLabel'),progressRing=document.querySelector('.progress-ring');
let mode=localStorage.getItem('thakir-mode')||'morning';
const welcome=document.querySelector('#welcome');
// Reset all dhikr counts automatically when a new local calendar day starts.
function resetDailyCounts(){
  const today=new Date().toLocaleDateString('en-CA');
  const savedDay=localStorage.getItem('thakir-count-date');
  if(savedDay!==today){
    for(let i=localStorage.length-1;i>=0;i--){
      const key=localStorage.key(i);
      if(key && (key.startsWith('count-') || key.startsWith('done-'))) localStorage.removeItem(key);
    }
    localStorage.setItem('thakir-count-date',today);
  }
}
resetDailyCounts();
function targetCount(benefit=''){const s=String(benefit).trim();if(/مائة/.test(s))return 100;if(/عشر/.test(s))return 10;if(/سبع/.test(s))return 7;if(/أربع/.test(s))return 4;if(/ثلاث/.test(s))return 3;if(/مرتين|مرتان/.test(s))return 2;return 1}
function getCount(m,i){const key=`count-${m}-${i}`,saved=Number.parseInt(localStorage.getItem(key),10);if(Number.isFinite(saved)&&saved>=0)return saved;if(localStorage.getItem(`done-${m}-${i}`)==='1'){const target=targetCount((m==='morning'?MORNING:EVENING)[i]?.benefit);localStorage.setItem(key,String(target));return target}return 0}
function stats(){const arr=mode==='morning'?MORNING:EVENING;let done=0,total=0;arr.forEach((z,i)=>{const t=targetCount(z.benefit);total+=t;done+=Math.min(getCount(mode,i),t)});return{done,total,pct:total?Math.round(done/total*100):0}}
function updateProgress(){const s=stats();progressText.textContent=s.pct+'%';progressRing.style.setProperty('--progress',s.pct+'%');progressLabel.textContent=s.pct===100?'أحسنت، اكتملت الأذكار':s.done?'أكمل أذكارك':'ابدأ أول ذكر'}
function render(){document.body.className=mode;morningTab.classList.toggle('active',mode==='morning');eveningTab.classList.toggle('active',mode==='evening');document.querySelector('#heroTitle').textContent=mode==='morning'?'ابدأ صباحك بالذكر':'اختم يومك بالذكر';document.querySelector('#greeting').textContent=mode==='morning'?'صباح الخير':'مساء الخير';list.innerHTML='';(mode==='morning'?MORNING:EVENING).forEach((z,i)=>{const target=targetCount(z.benefit),count=Math.min(getCount(mode,i),target),el=document.createElement('article');el.className='zekr';el.innerHTML=`<div class="text">${z.text}</div>${z.benefit?`<div class="benefit">${z.benefit}</div>`:''}<button class="mark${count>=target?' done':''}" aria-label="الذكر ${count} من ${target}" ${count>=target?'disabled':''}>${count}/${target}</button>`;const advance=()=>{if(getCount(mode,i)>=target)return;const next=Math.min(getCount(mode,i)+1,target);localStorage.setItem(`count-${mode}-${i}`,String(next));render()};el.addEventListener('click',e=>{if(e.target.closest('.mark'))return;el.classList.remove('ripple');void el.offsetWidth;el.classList.add('ripple');advance()});el.querySelector('.mark').onclick=e=>{e.stopPropagation();el.classList.remove('ripple');void el.offsetWidth;el.classList.add('ripple');advance()};list.appendChild(el)});updateProgress()}
morningTab.onclick=()=>{mode='morning';localStorage.setItem('thakir-mode',mode);render()};eveningTab.onclick=()=>{mode='evening';localStorage.setItem('thakir-mode',mode);render()};
document.querySelector('#continueBtn').onclick=()=>document.querySelector('#adhkar').scrollIntoView({behavior:'smooth',block:'start'});
document.querySelector('#startBtn').onclick=()=>{localStorage.setItem('thakir-welcomed','1');welcome.classList.add('hidden');welcome.setAttribute('aria-hidden','true')};
if(localStorage.getItem('thakir-welcomed')==='1')welcome.classList.add('hidden');else welcome.setAttribute('aria-hidden','false');
async function prayerTimes(){try{const r=await fetch('https://api.aladhan.com/v1/timingsByCity?city=Jeddah&country=Saudi%20Arabia&method=4');const j=await r.json(),t=j.data.timings;nextPrayer.textContent=`الفجر ${t.Fajr}  •  العصر ${t.Asr}`;scheduleInPage('fajr',t.Fajr);scheduleInPage('asr',t.Asr)}catch(e){nextPrayer.textContent='فعّل الإنترنت لحساب وقت الفجر والعصر في جدة'}}
function scheduleInPage(type,time){const [h,m]=time.split(':').map(Number),now=new Date(),target=new Date();target.setHours(h,m,0,0);if(target<=now)target.setDate(target.getDate()+1);setTimeout(()=>{if(Notification.permission==='granted')new Notification(type==='fajr'?'أذكار الصباح':'أذكار المساء',{body:type==='fajr'?'حان وقت أذكار الصباح 🌅':'حان وقت أذكار المساء 🌙',icon:'icon.png'});scheduleInPage(type,time)},target-now)}
const PUSH_WORKER='https://divine-tooth-9dc5.sultanyaghmor1544.workers.dev';
function urlBase64ToUint8Array(base64String){const padding='='.repeat((4-base64String.length%4)%4),base64=(base64String+padding).replace(/-/g,'+').replace(/_/g,'/'),raw=atob(base64),output=new Uint8Array(raw.length);for(let i=0;i<raw.length;++i)output[i]=raw.charCodeAt(i);return output}
async function enablePush(){if(!('Notification'in window)||!('serviceWorker'in navigator)||!('PushManager'in window)){alert('هذا الجهاز لا يدعم إشعارات Push للموقع.');return false}const permission=await Notification.requestPermission();if(permission!=='granted'){document.querySelector('#notifyStatus').textContent='الإشعارات غير مفعّلة';return false}const registration=await navigator.serviceWorker.ready;let subscription=await registration.pushManager.getSubscription();if(!subscription){const keyResponse=await fetch(PUSH_WORKER+'/vapid-public-key');if(!keyResponse.ok)throw new Error('تعذر جلب مفتاح الإشعارات');const publicKey=(await keyResponse.text()).trim();subscription=await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:urlBase64ToUint8Array(publicKey)})}const response=await fetch(PUSH_WORKER+'/subscribe',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(subscription)});if(!response.ok)throw new Error('تعذر حفظ اشتراك الإشعارات');document.querySelector('#notifyStatus').textContent='تم تفعيل الإشعارات ✅';return true}
notifyBtn.onclick=async()=>{try{notifyBtn.disabled=true;document.querySelector('#notifyStatus').textContent='جاري تفعيل الإشعارات…';await enablePush()}catch(e){console.error(e);document.querySelector('#notifyStatus').textContent='تعذر تفعيل الإشعارات — حاول مرة أخرى'}finally{notifyBtn.disabled=false}};
const modal=document.querySelector('#settingsModal');document.querySelector('#settingsBtn').onclick=()=>modal.classList.add('open');document.querySelector('#closeSettings').onclick=()=>modal.classList.remove('open');modal.addEventListener('click',e=>{if(e.target===modal)modal.classList.remove('open')});
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');render();prayerTimes();

// Subtle touch/mouse parallax for the night sky.
(function(){const root=document.body;let raf=0;function move(x,y){cancelAnimationFrame(raf);raf=requestAnimationFrame(()=>{const dx=(x/innerWidth-.5)*10,dy=(y/innerHeight-.5)*8;root.style.setProperty('--sky-x',dx+'px');root.style.setProperty('--sky-y',dy+'px')})}window.addEventListener('pointermove',e=>move(e.clientX,e.clientY),{passive:true});})();
